# cloudbuild.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:${BUILD_ID}', '.']

  # Push the Docker image to Artifact Registry (AR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:${BUILD_ID}']

  # Deploy the service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'food-delivery-frontend'  # Replace with your desired service name
      - '--image'
      - 'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:${BUILD_ID}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-south1'
      - '--allow-unauthenticated' #Important for testing. Remove for production
      - '--port'
      - '8080'

images:
  - 'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:${BUILD_ID}'

options:
  substitution_option: 'ALLOW_LOOSE' #Allows $BUILD_ID and $PROJECT_ID to be missing, so you can run locally
  
options:
  logging: CLOUD_LOGGING_ONLY
